### ISSUE TITLE
[task] should the hooks be called before or after `HostEnsureCanCompileStrings`?

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#11]

**Comment by erights** [comment]
Since HostEnsureCanCompileStrings is not given the string, it's hard to see what the practical differences would be. Btw, when looking at it, I was surprised to see two realms being passed to HostEnsureCanCompileStrings . Why is that?

Should HostEnsureCanCompileStrings be given the string? If so, then the order would of course make a big difference.

**Comment by caridy** [comment]
The main difference here is that if a piece of code is evaluated in a realm (from the realm itself via eval invocation), and that realm is suppose to prevent compilation of strings (via `HostEnsureCanCompileStrings`), but the realm creator provides a hook that implements an alternative evaluation process (its own JS compiler, or evaluation in a worker, or whatever crazy mechanism users come up with), then it does matter if we call it before or after. But considering that if you have a way to define the hook is because you have access to the power object, and you were responsible for defining the alternative mechanism, and the security flags of the new realm, then it is probably best to execute that right after, preserving the ability to execute the evaluation hook that might or might not implement an alternative evaluation, and only call `HostEnsureCanCompileStrings` if the hook returns a string value ready to be evaluated.

As for the question about the arguments of `HostEnsureCanCompileStrings`, I don't think the string value is important, it is just the intent what matters, and I think the reason why both realms (caller and callee) are provided is to leave the door open for extra flagging at the realm level. Imagine the case where a realm is created with some flag for `HostEnsureCanCompileStrings` to prevent evaluation from within, but whoever have access to the realm power object, can invoke evaluation via `realmObj.eval("something")`. Maybe @domenic knows better.

**Comment by domenic** [comment]
On the web both realms are checked. If either are blocked by CSP then the compilation is disallowed. This covers cases like `window2.eval("foo")` from inside `window1`. If either `window1` or `window2` is disallowed from executing script by CSP, the call will fail.

**Comment by caridy** [comment]
@erights I think we can now close this one since we have settled of calling the hook before `HostEnsureCanCompileStrings`.

**Comment by erights** [comment]
Seems fine.
