### ISSUE TITLE
Shim: Document unsupported shortcut <function instance>.constructor === Function

### ISSUE THREAD

**Issue by jfparadis** [tc39/proposal-realms#116]
We need to document this limitation.

Older libraries might do a constructor check in lieu of `typeof` operator.
```js
function isFunction(fn) {
   return !!fn && fn.constructor === Function;
}
```
There should not be any reasons to do this, `typeof` is not the expensive string comparison often claimed.
https://jsperf.com/typeof-function-vs-constructor

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
