### ISSUE TITLE
items to resolve before we can recommend the shim for use

### ISSUE THREAD

**Issue by warner** [tc39/proposal-realms#136]
* ways in which the shim diverges from the spec
  * divergences that need to be reconciled
  * shim limitations that won't get fixed
* list of good/safe use cases/examples (passing primitives in)
* list of not-yet-safe use cases/examples (passing an object into a realm from a non-frozen realm)
* list of not-yet-functional use cases
* settle on (get comfortable with) the division between RootRealm/Compartment rather than a full spectrum
* "feral object/realm": we removed getIntrinsics because it was too hard to use safely. endowments from the outside have similar problem. find a way to make these safe to use. `console` is a good example.

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
