### ISSUE TITLE
Primal realm should only be repaired if compartments are created into it 

### ISSUE THREAD

**Issue by jfparadis** [tc39/proposal-realms#144]
Intrinsics from the primal realm should never be accessible from new root realms (and their compartments). For that reason, legacy accessors and functions constructors don't need to be repaired if suspicious code only runs in new root realms.

To reduce side effects, it might be advantageous to keep the primal realm intact, and only repair it when confinement needs to be maintained, that is when compartments are created into it.

**Comment by caridy** [comment]
Since this proposal doesn't include compartments anymore (that will be a separate proposal), we can close this one.
