### ISSUE TITLE
Removing iframe after capturing the global?

### ISSUE THREAD

**Issue by jfparadis** [tc39/proposal-realms#145]
In a browser, the shim creates an iframe for each new root realm to get a new set of intrinsics. Those iframes only obtain a global scope once the iframe is inserted in the DOM. They are never removed because the global scope gets destroyed (TODO: this should be documented).

The tests below suggeststhat a new global is created upon every insertion of the iframe in the DOM and deleted upon removal of the iframe from the DOM. Even if pointers to global objects are captured prior to removal, those objects cease to function normally, for example `eval()` returns undefined (and even stops throwing on syntax errors).

```js
iframe = document.createElement('iframe');
iframe.contentWindow
// null 

document.body.append(iframe);
iframe.contentWindow
// Window {postMessage: ƒ, ...} (as expected)

win = iframe.contentWindow;
win.Object
// ƒ Object() { [native code] } (as expected)

evaluator = win.eval
evaluator("1 + 1");
// 2 (as expected)

document.body.remove(iframe)
iframe.contentWindow
// null (as expected)

win.Object
// undefined (properties of the global object are removed)

evaluator("1 + 1");
// undefined (not functional)

document.body.appendChild(iframe);
evaluator("1 + 1");
// undefined (not functional)
win.eval
// undefined (global object apparently not reused)
iframe.contentWindow.eval("1 + 1")
// 2 (expected)
```

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.

For the record, we were able to resolve this in https://github.com/caridy/secure-javascript-environment
