### ISSUE TITLE
shim: if initialization fails, make the Realm unusable?

### ISSUE THREAD

**Issue by warner** [tc39/proposal-realms#153]
At today's meeting, we discussed what the shim (or user code which is initializing a new Realm, e.g. by removing all primordials that aren't on some whitelist) should do when initialization fails. There is an error signal, but if user code ignores that, we might want to defensively avoid leaving around the attractive nuisance of a partially-initialized Realm. The old Caja/SES code reacted to this by replacing many evaluators with versions that throw errors when used. We might want to do a similar "burn the world" technique here.

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
