### ISSUE TITLE
Just noting hazard: optimizer must not include "eval"

### ISSUE THREAD

**Issue by erights** [tc39/proposal-realms#171]
All the own property names on the safeGlobal that are non-configurable, non-writable data properties are candidates for including in the optimizer's list of optimized variable name lookups. These names are looked up on the scopeProxy before the normal call to direct eval. If we allowed "eval" to be one of these optimized names, then it might trigger the scopeHander's "provide unsafeEval the first time" logic, enabling unsafeEval to be captured by one of these in-scope variables.

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
