### ISSUE TITLE
Just noting hazard: handler must not leak scopeProxy to global accessor's getter

### ISSUE THREAD

**Issue by erights** [tc39/proposal-realms#172]
Say the user installs an accessor property on the safeGlobal. If the handler reflects these lookups onto this accessor property using Reflect.get in the "obvious" way, it would leak the scopeProxy as the receiver, i.e., as the object to pass to the getter as its this-binding.

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
