### ISSUE TITLE
Just noting hazard: optimizer must not leak scopeProxy

### ISSUE THREAD

**Issue by erights** [tc39/proposal-realms#173]
See related https://github.com/tc39/proposal-realms/issues/171 https://github.com/tc39/proposal-realms/issues/172

All the own property names on the safeGlobal that are non-configurable, non-writable data properties are candidates for including in the optimizer's list of optimized variable name lookups. These names are looked up on the scopeProxy before the normal call to direct eval.

If the user could somehow install an accessor property that is looked up during this lookup, the getter might dereference a free variable "eval". This might trigger the scopeHander's "provide unsafeEval the first time" logic, enabling unsafeEval to be captured by that free variable lookup.

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
