### ISSUE TITLE
shim: expose safe eval inside the compartment

### ISSUE THREAD

**Issue by warner** [tc39/proposal-realms#182]
In https://github.com/Agoric/SES/issues/5 we noticed that it would be awfully nice to have access to the safe (indirect, two-argument) evaluator function from *inside* a realm. If you created the new RootRealm or Compartment, then you have access to the "realm controller object", which we usually store in a variable named `r`. Thus from the *outside* you can do `r.evaluate(code, endowments)`. But currently, from the inside, you only have access to plain old (indirect) `eval()`, which doesn't accept endowments.

Currently `SES.confine()` (which seeks to provide this two-argument functionality) is bound to a wrapper around the realm's `r.evaluate()`, with extra code to catch exceptions and replace them with types from inside the realm. And of course that `r.evaluate()` is bound to a wrapper around the realm's internal `safeEvalWhichTakesEndowments`, which catches exceptions to replace them with types from *outside* the realm. So any exceptions raised in the code passed into`SES.confine()` will be wrapped *twice*, which is unfortunate, and probably introduces additional identity discontinuities.

So we're thinking that maybe `Realm.confine(code, endowments)` could be bound to the internal `safeEvalWhichTakesEndowments` function. We considered `Realm.eval` or `Realm.evaluate`, but it seems like that might be confused with `r.evaluate` (from outside). On the other hand, when `r.evaluate(code, endowments)` from the outside behaves exactly the same way as `Realm.evaluate(code, endowments)` on the inside (modulo exception-wrapping), maybe it *would* be a good idea to use the same name on both sides. I'm not sure.

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
