### ISSUE TITLE
Old mentions of Realm must be updated to distinguish "root realm" vs "compartment"

### ISSUE THREAD

**Issue by erights** [tc39/proposal-realms#186]
See https://github.com/tc39/ecma262/issues/1333#issuecomment-432655824

**Comment by erights** [comment]
Not just ecma specs. For example, https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects states:

> There is always a 1-to-1-to-1 mapping between JavaScript realms, global objects, and environment settings objects:

No longer true.

**Comment by erights** [comment]
See also https://github.com/whatwg/html/issues/1430

**Comment by caridy** [comment]
Since this proposal is not longer tracking compartments vs root realms, we can close this.
