### ISSUE TITLE
[shim] document how to run the tests for the shim

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#190]

**Comment by warner** [comment]
I guess the text will be to run `npm install` followed by `npm run-script shim:test`. Where would we like this, in the main README?

**Comment by caridy** [comment]
@warner  usually you should have that in the CONTRIBUTING.md in case someone decides to contribute.

**Comment by ljharb** [comment]
Convention is that `npm install && npm test` is sufficient to run all tests. Regardless of what’s documented, it’d be ideal to ensure that works.

**Comment by caridy** [comment]
This is related to the Shim implementation, closing since it was moved into https://github.com/Agoric/realms-shim.
