### ISSUE TITLE
Add instance method for creating compartments

### ISSUE THREAD

**Issue by Jamesernator** [tc39/proposal-realms#209]
(This is an issue for [this comment](https://github.com/tc39/proposal-realms/issues/156#issuecomment-465854989))

Currently compartments can only be created via a static method from within a Realm. This is both inconvenient and unsafe to access if you have created a new root Realm.

Example:

```js
const realm = Realm.makeRootRealm();

const compartment1 = realm.global.Realm.makeCompartment();

compartment1.evaluate(`
  Object.defineProperty(Realm, "makeCompartment", {
    value: function badThing() {
      // Do something that isn't make a compartment
    },
  });
`);

// TAMPERED!
const compartment2 = realm.global.Realm.makeCompartment();

const realm2 = Realm.makeRootRealm();

// Even if we capture makeCompartment beforehand the prototype
// can still be tampered
const makeCompartment = realm2.global.Realm.makeCompartment;

const compartment3 = makeCompartment();

compartment3.evaluate(`
  Object.defineProperty(Realm.prototype, "evaluate", {
    value: function badThing() {
      // Do bad thing that isn't evaluate
    },
  });
`)

// This is safe
const compartment4 = makeCompartment();

// But this is TAMPERED!
compartment4.evaluate(`something`)
```

In order to prevent this and generally be more convenient I propose the simple addition of `Realm.prototype.makeCompartment` method (in addition to the static form).

This method would return a new compartment with the same intrinsics as the Realm instance but its own prototype would be that of our current `Realm.prototype` not the inner realm.

e.g.:

```js
const realm = Realm.createRootRealm();

const InnerRealm = realm.global.Realm;

const compartment = realm.makeCompartment();
const innerCompartment = InnerRealm.makeCompartment();

compartment instanceof Realm; // True, safe from tampering from within realm
innerCompartment instanceof InnerRealm // True, possibly tampered with
```

**Comment by caridy** [comment]
Since this proposal is not longer tracking the compartments, that will be a separate proposal, we can now close this.
