### ISSUE TITLE
[shim] implement evaluator for generator functions

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#27]

**Comment by jfparadis** [comment]
@caridy What do you need here?

**Comment by caridy** [comment]
I don't remember. Maybe @erights remembers.

**Comment by erights** [comment]
https://github.com/google/caja/blob/master/src/com/google/caja/ses/startSES.js#L1079
https://github.com/tvcutsem/es-lab/blob/master/src/ses/startSES.js#L1068

Given[1] that we have a debugged scheme for turning param text plus body text into a function expression, then we can reuse the scheme for the various different function constructors merely by varying the prefix: `function` vs `function*` vs `async function` vs `async function*`. Somewhere I have a CL that factors out this prefix in order to reuse the rest of the function constructor emulation logic.

**Comment by jfparadis** [comment]
Great, we will look into these examples. Let me put a PR with new code to get this going. We couls also use our code.

I have two concerns with the goal "implement evaluator for generator functions":
1. How useful is it? 

Only Function is exported on the global object. The other 3 constructors are only accessible by climbing up the prototype chain, and I question how likely this can be an issue for compatibility. 

2. How complex is it? 

To prevent identity discontinuities, the prototype chain is shared between realms, therefore all four function evaluators need to be scope to each realm, something difficult considering that they are shared. The best we could probably do anyway is to scope them to only safe shared globals, which can be confusing as `Function("return window.foo")` will work differently than `Function.prototype.constructor("return window.foo")`. 

Here is an alternative approach, which is what we do at Salesforce (link below):

1. All four function constructors are tamed with noop evaluators (noop = they return an empty function instance upon invocation), and all of them inherit from Function's noop. It is simpler and less confusing than creating a third type of evaluation, not scoped to real, not scoped to out-of-realm global either.

2. Function is scoped, meaning a Function is created for each realm and it uses the realm's eval  evaluator. The out-of-realm Function global (eg window.Function) remains unchanged meaning that Function evaluation outside of realms are unaffected. 

3. To preserve identity continuity in each realm eg `(function (){}) instance of Function` where Function is the realm's tamed Function evaluator, we set the Symbol.hasInstance of those realm Function to check against the noop Function of the out-of-realm function, something along the lines:

``` js
  defineProperties(RealmFunction, Symbol.hasInstance, {
      value: v => v instanceof NoopFunction
  });
```

Here is our code, (inspired from SES in some areas with proper credits):
https://github.com/forcedotcom/aura/blob/master/aura-resources/src/main/resources/aura/resources/lockerservice/aura-locker.js#L574

```js
/**
 * This block replaces the original Function constructor, and the original
 * %GeneratorFunction% %AsyncFunction% and %AsyncGeneratorFunction%, with
 * safe replacements that preserve SES confinement. After this block is done,
 * the originals should no longer be reachable.
 */
function repairFunctions(lockerRec) {
  const { unsafeGlobal } = lockerRec;
  const hasAsyncIteration = typeof unsafeGlobal.Symbol.asyncIterator !== 'undefined';

  // Here, the order of operation is important: Function needs to be
  // repaired first since the other constructors need it.
  repairRootFunction(lockerRec, 'Function', 'function');
  repairRootFunction(lockerRec, 'GeneratorFunction', 'function*');
  repairRootFunction(lockerRec, 'AsyncFunction', 'async function');
  if (hasAsyncIteration) {
    repairRootFunction(lockerRec, 'AsyncGeneratorFunction', 'async function*');
  }
}
```

```js
/**
 * The process to repair constructors:
 * 1. Obtain the prototype from an instance
 * 2. Create a substitute noop constructor
 * 3. Replace its prototype property with the original prototype
 * 4. Replace its prototype property's constructor with itself
 * 5. Replace its [[Prototype]] slot with the noop constructor of Function
 */
function repairRootFunction(lockerRec, functionName, functionDecl) {
  const { unsafeGlobal, unsafeEval, unsafeFunction } = lockerRec;

  const RootFunctionInstance = unsafeEval(`(${functionDecl}(){})`);
  const RootFunctionPrototype = getPrototypeOf(RootFunctionInstance);

  const NoopFunction = unsafeFunction('return function(){}');
  defineProperties(NoopFunction, {
    name: {
      value: functionName
    },
    toString: {
      value: () => `function ${functionName}() { [native code] }`
    }
  });

  defineProperty(NoopFunction, 'prototype', { value: RootFunctionPrototype });
  defineProperty(RootFunctionPrototype, 'constructor', { value: NoopFunction });

  // Prevent loop in case of Function.
  if (NoopFunction !== unsafeGlobal.Function.prototype.constructor) {
    setPrototypeOf(NoopFunction, unsafeGlobal.Function.prototype.constructor);
  }
}
```

```js
/**
 * A safe version of the native Function which relies on
 * the safety of evalEvaluator for confinement.
 */
function createFunctionEvaluator(sandbox) {
  const evaluator = function(...params) {
    const body = params.pop() || '';
    const src = `
(function(${params.join(',')}) {
  ${body}
})`;
    // evalEvaluator is created after FunctionEvaluator,
    // so we can't link directly to it.
    return sandbox.evalEvaluator(src);
  };

  // Ensure that the different Function instances of the different
  // sandboxes all answer properly when used with the instanceof
  // operator to preserve indentity.
  const NoopFunction = sandbox.unsafeFunction.prototype.constructor;

  // Mimic the native signature.
  defineProperties(evaluator, {
    name: {
      value: 'Function'
    },
    toString: {
      value: () => 'function Function() { [native code] }'
    },
    [Symbol.hasInstance]: {
      value: v => v instanceof NoopFunction
    }
  });

  return freeze(evaluator);
}
```

**Comment by jfparadis** [comment]
I would like to highlight two differences from SES in the code above.

**Difference 1.**  We preserve the original behavior of Function for use outside of realms. The difference is  that don't export the tamed Function back on the global:

````
global.Function = FakeFunction
````
https://github.com/tvcutsem/es-lab/blob/master/src/ses/startSES.js#L1065

Where global is set to `this`.
```
(function hookupSESModule(global) {
  "use strict";
    // [...]
    ses.startSES(global, 
    // [...]
})(this);
```
https://github.com/google/caja/blob/1056be89dad487f9178d89f462fe5cb207c7e604/src/com/google/caja/ses/hookupSES.js#L27

**Difference 2.** We create separate instances of Function for each compartment which execute in the context of each compartment's global.

This is the normal behavior of Function.

```js
a = 1
function Foo() {}
console.log(Function("return a")())
console.log(Foo instanceof Function)
// 1
// true
```

Assume we have compartment A and B which tame Function differently so that two instances are necessary:

```
function AFunction(src) { with (AGlobal) { return eval(`(function() { ${src} })`) } } 
function BFunction(src) { with (BGlobal) { return eval(`(function() { ${src} })`) } } 
const AGlobal = {Function: AFunction};
const BGlobal = {Function: BFunction};

with (AGlobal) {
   a = 2
   console.log(Function("return a")())
   console.log(Foo instanceof Function)
}
with (BGlobal) {
   a = 3
   console.log(Function("return a")())
   console.log(Foo instanceof Function)
}
//  2 (correct)
// false (incorrect)
//  3 (correct)
// false (incorrect)
```

This is the proposed solution to this identity discontinuity (reusing the same globals)

```
Object.defineProperty(AFunction, Symbol.hasInstance, {
	value: v => v instanceof Function
})
Object.defineProperty(BFunction, Symbol.hasInstance, {
	value: v => v instanceof Function
})

with (AGlobal) {
   console.log(Function("return a")())
   console.log(Foo instanceof Function)
}
with (BGlobal) {
   console.log(Function("return a")())
   console.log(Foo instanceof Function)
}
//  2 (correct)
// true (correct)
//  3 (correct)
// true (correct)
```

With this approach, the Frozen Realm shim can coexist with other code loaded on the main window (Function is unchanged) with minimal side-efffects, and all compartments can use a Function evaluator that implements more closely the default behavior.

**Comment by jfparadis** [comment]
Closing this as the implementation is done.
