### ISSUE TITLE
Synchronous import?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-realms#274]
Does it possible to `import()` in a synchronous manner like an ordinary import?

**Comment by leobalter** [comment]
The Realm.prototype.import is meant to mimic the import expression and we don't have many other extensions to the API in this specific proposal.

One can still have import declarations in the script loaded inside the Realms.

**Comment by leobalter** [comment]
@Jack-Works Please let me know if there any other questions about this, I'll close the issue for now.
