### ISSUE TITLE
[shim][investigation] find a way to support global-contour for `let` and `const`

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#31]

**Comment by erights** [comment]
And `class`, for which the issues should be identical to `let`.

**Comment by erights** [comment]
We just added an "endowments" mechanism to the shim which is best understood as shimming an approximation of some support for the global contour for `let` and `const`. Turns out to be very powerful and lightweight. Obviously, we need to examine the corresponding changes needed for the spec.

**Comment by caridy** [comment]
closing this since it is related to the shim.
