### ISSUE TITLE
specify how to create a new realm that inherit all intrinsics/primordials from parent realm

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#51]
This will allow us to create multiple realms sharing the primordials but still creating the global object and the `this` value. This is somehow equivalent to the previously discussed Scopes concept.

**Comment by jfparadis** [comment]
Sharing the primordials has been solved with `{ intrinsics: "inherit" }` as coded in the the current specs and supported in the shim. 

Can we close this @caridy?
